### ISSUE TITLE
Start / Restart Arduplane

### ISSUE THREAD

**Issue by kikislater** [Parrot-Developers/arduplane-disco-manifest#3]
I read documentation but my disco stay on parrot firmware. I connected it with apm planner or qgroundcontrol through wifi and udp port 14550 and have same status : armed

So I wonder what is meaning by pressing 3 times on/off button : 
- Disco power off, I have to press 3 times ? It stay on stock autopilot
- Disco power on, pressing 3 times : it keeps stock autopilot 

Firmware 1.4.1 and APM successfully updated : 
 ```
./update.sh 
Connected to 192.168.42.1.
220 Operation successful
---> SYST
215 UNIX Type: L8
Remote system type is UNIX.
Using binary mode to transfer files.
---> TYPE I
200 Operation successful
---> MKD internal_000/APM/
257 Operation successful
---> PORT 192,168,42,67,184,51
200 Operation successful
---> STOR internal_000/APM/apm-plane-disco
150 Ok to send data
226 Operation successful
678268 bytes sent in 0,24 seconds (2,69 Mbytes/s)
---> QUIT
221 Operation successful
```

**Comment by kikislater** [comment]
- APM folder is not the right folder to put the file
- There is an existing ardupilot folder
- The correct name of the file has to be arduplane and not apm-plane-disco like parrot share.

**Comment by bhamilton1co** [comment]
Thanks for this!
